#!/bin/bash

set -euf -o pipefail

readonly WORKING_DIR="$PWD"
readonly OUTPUT_DIR="/tmp/deploy"
readonly DEPENDENCIES_DIR=$(python -c "from distutils.sysconfig import get_python_lib; print(get_python_lib())")

if [[ $DEPENDENCIES_DIR == "" ]]; then
    echo "Cannot find site-packages directory" >&2
    exit 1
fi

if [[ -z $1 ]]; then
    echo "Usage: $0 <output zip>" >&2
    exit 1
fi

readonly OUTPUT_ZIP="$1"

if [[ -d $OUTPUT_DIR ]]; then
    echo "Output dir already exists" >&2
    exit 1
fi

mkdir "$OUTPUT_DIR"
rsync -a "$DEPENDENCIES_DIR/" "$OUTPUT_DIR"
rsync -a pushover_notification.py "$OUTPUT_DIR"
du -sh "$OUTPUT_DIR"

cd "$OUTPUT_DIR"  # cannot have container dir in zip
zip -qr9 "$OUTPUT_ZIP" .
cd "$WORKING_DIR"
du -sh "$OUTPUT_ZIP"
